### ISSUE TITLE
#bug Height Bug

### ISSUE THREAD

**Issue by ikeyu-dev** [polaris-proto/polaris-stage#4]
@sasanqua-dev  
When displayed on a computer with a special screen width, the height does not match.

**Comment by sasanqua-dev** [comment]
Please give me some additional information.

- What browser do you use?
- Please tell me your screen size.

**Comment by ikeyu-dev** [comment]
I am using Google Chrome and my screen width is 1920*1200.

**Comment by sasanqua-dev** [comment]
![image](https://github.com/user-attachments/assets/b9fd81d4-ea9f-4ecf-a525-6a74146a871a)

Could not reproduce.

**Comment by ikeyu-dev** [comment]
ok, thanks.
