### ISSUE TITLE
There are no directory, "src/data".

### ISSUE THREAD

**Issue by ikeyu-dev** [polaris-proto/polaris-stage#5]
The "data" directory does not exist directly under the "src" directory.

**Comment by sasanqua-dev** [comment]
@uyuyuu09  please tell me more information about this issue

**Comment by ikeyu-dev** [comment]
When we clone this application, there no such directory "src/data".
Please make that directory.
(Some people maybe forget making that directory when he/she clone this application, so....)

**Comment by sasanqua-dev** [comment]
ok
I will create soon.
